version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./node:/app
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

networks:
  node-network:
    driver: bridge
